name: SketchOff
exclude:
 - Gemfile
 - Gemfile.lock
 - Guardfile
 - sketch-off-landing.sublime-project
 - sketch-off-landing.sublime-workspace
 - README.md
 - deploy.sh
 - mask.psd
sass:
    sass_dir: assets/css
    style: :compressed
coffee:
    style: :compressed
